version: "3.9"

services:
  
  webapp:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=product_service;Username=admin;Password=admin;
    depends_on:
      db:
        condition: service_healthy
    
  db:
    container_name: product-service-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_service"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data: